p8105\_hw1\_kb3066
================
Kaila Boyer
9/22/2021

link to repo: <https://github.com/kboyer-ops/p8105_hw1_kb3066.git>

## Loading packages

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

Creating dataframe

``` r
data_p1 <- tibble(
   r_sample = rnorm(10), 
   log_vec = r_sample > 0, 
   char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),  
   fac_vec = factor(c("high", "high", "high", "middle", "middle", "middle", "middle", "low", "low", "low"))
)
```

Taking mean of each variable in data frame

``` r
mean(pull(data_p1,r_sample))
```

    ## [1] -0.09590107

``` r
mean(pull(data_p1,log_vec))
mean(pull(data_p1,char_vec))
mean(pull(data_p1,fac_vec))
```

Taking the mean of the logical vector, character vector, and the factor
vector was unsuccessful.

``` r
as.numeric(pull(data_p1,log_vec))
as.numeric(pull(data_p1,char_vec))
as.numeric(pull(data_p1,fac_vec))
```

Converting the logical and factor vector to a numeric before taking the
mean is successful. True/false in the logical vector were converted to 1
and 0, respectively, so the mean was able to be calculated. Each level
in the factor vecter were assigned a number (1, 2, or 3), which allowed
us to find the mean. This could not happen with the character vector, so
converting it to a numeric and trying to calculate the mean were
unsuccessful.

## Problem 2

Loading the penguins dataset

``` r
data("penguins", package = "palmerpenguins")
```

Short description of penguins dataset

``` r
head(penguins)
```

    ## # A tibble: 6 × 8
    ##   species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g sex  
    ##   <fct>   <fct>           <dbl>         <dbl>            <int>       <int> <fct>
    ## 1 Adelie  Torge…           39.1          18.7              181        3750 male 
    ## 2 Adelie  Torge…           39.5          17.4              186        3800 fema…
    ## 3 Adelie  Torge…           40.3          18                195        3250 fema…
    ## 4 Adelie  Torge…           NA            NA                 NA          NA <NA> 
    ## 5 Adelie  Torge…           36.7          19.3              193        3450 fema…
    ## 6 Adelie  Torge…           39.3          20.6              190        3650 male 
    ## # … with 1 more variable: year <int>

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(pull(penguins,flipper_length_mm), na.rm = TRUE)
```

    ## [1] 200.9152

``` r
Hmisc::describe(penguins)
```

The penguins dataset has 344 rows and 8 columns. The column names are
species (factor of 3), island (factor of 3), bill length (number in mm),
bill depth (number in mm), flipper length (number in mm), body mass
(number in g), sex (factor of 2), and year (factor of 3. The mean
flipper length is 200.9 mm.

Scatterplot of flipper length vs. bill length

``` r
ggplot(penguins, aes(x = bill_length_mm, y =flipper_length_mm , color = species)) + geom_point()
```

![](p8105_hw1_kb3066_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->

``` r
ggsave("hw1_scatterplot.pdf")
```

    ## Saving 7 x 5 in image
